In [ ]:
import numpy as np

def input_handling(input_string):
  binary_form = []
  for char in input_string:
    binary_value = format(ord(char), '08b')
    for bit in binary_value:
      binary_form.append(int(bit))

  binary_array = np.array(binary_form).reshape(-1, 8)
  return(binary_array)

In [ ]:
def initial_permutation(binary_array):
  new_array = np.zeros((8, 8), dtype='int')
  flattened_array = binary_array.flatten()
  permutation_format = np.array([[58, 50, 42, 34, 26, 18, 10, 2],
                                 [60, 52, 44, 36, 28, 20, 12, 4],
                                 [62, 54, 46, 38, 30, 22, 14, 6],
                                 [64, 56, 48, 40, 32, 24, 16, 8],
                                 [57, 49, 41, 33, 25, 17, 9, 1],
                                 [59, 51, 43, 35, 27, 19, 11, 3],
                                 [61, 53, 45, 37, 29, 21, 13, 5],
                                 [63, 55, 47, 39, 31, 23, 15, 7]]) - 1

  for i in range(8):
    for j in range(8):
      new_array[i, j] = flattened_array[permutation_format[i, j]]
  return new_array

In [ ]:
def swap(array):
  swapped_array = np.zeros((8, 8), dtype='int')
  swapped_array[:4, :] = array[4:, :]
  swapped_array[4:, :] = array[:4, :]
  return swapped_array

In [ ]:
def final_permutation(binary_array):
  new_array = np.zeros((8, 8), dtype='int')
  flattened_array = binary_array.flatten()
  permutation_format = np.array([[40, 8, 48, 16, 56, 24, 64, 32],
                               [39, 7, 47, 15, 55, 23, 63, 31],
                               [38, 6, 46, 14, 54, 22, 62, 30],
                               [37, 5, 45, 13, 53, 21, 61, 29],
                               [36, 4, 44, 12, 52, 20, 60, 28],
                               [35, 3, 43, 11, 51, 19, 59, 27],
                               [34, 2, 42, 10, 50, 18, 58, 26],
                               [33, 1, 41, 9, 49, 17, 57, 25]]) - 1

  for i in range(8):
    for j in range(8):
      new_array[i, j] = flattened_array[permutation_format[i, j]]
  return new_array

In [ ]:
binary_array = input_handling('PAKISTAN')
print(binary_array)

[[0 1 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 1]
 [0 1 0 0 1 0 1 1]
 [0 1 0 0 1 0 0 1]
 [0 1 0 1 0 0 1 1]
 [0 1 0 1 0 1 0 0]
 [0 1 0 0 0 0 0 1]
 [0 1 0 0 1 1 1 0]]


In [ ]:
new_array = initial_permutation(binary_array)
print(new_array)

[[1 1 1 1 1 1 1 1]
 [0 0 1 1 0 0 0 1]
 [1 0 1 0 0 0 0 0]
 [0 1 0 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0]
 [1 0 0 1 0 1 0 0]]


In [ ]:
swapped_array = swap(new_array)
print(swapped_array)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0]
 [1 0 0 1 0 1 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 1 1 0 0 0 1]
 [1 0 1 0 0 0 0 0]
 [0 1 0 1 1 1 1 0]]


In [ ]:
final_array = final_permutation(swapped_array)
print(final_array)

[[1 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 1 0]
 [1 0 0 0 0 1 1 1]
 [1 0 0 0 0 1 1 0]
 [1 0 1 0 0 0 1 1]
 [1 0 1 0 1 0 0 0]
 [1 0 0 0 0 0 1 0]
 [1 0 0 0 1 1 0 1]]


In [ ]:
def des_decrypt(final_array):
  array1 = initial_permutation(final_array)
  array2 = swap(array1)
  array3 = final_permutation(array2)
  text = ''
  for row in array3:
      binary_string = ''.join(map(str, row))
      ascii_value = int(binary_string, 2)
      character = chr(ascii_value)
      text += character
  print(text)

In [ ]:
des_decrypt(final_array)

PAKISTAN
